server:
  port: 18081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'
    loadbalancer:
      ribbon:
        enabled:true
  application:
    name: business-service

seata:
  enabled: true
  application-id: ${spring.application.name}

  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      dataId: "seata.properties"
      username: 'nacos'
      password: 'nacos'
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: 'nacos'
      password: 'nacos'

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
logging:
  level:
    io:
      seata: debug

