server:
  port: 19096

spring:
  application:
    name: webClient-service-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    # label routing configuration
    governance:
      routing:
        region: dev
        zone: zone1
      # rule: RandomRule
